sm8250-common: Add missing QSPM blobs
error: vendor/xiaomi/sm8250-common/Android.bp:257:1: "libadreno_app_profiles" depends on undefined module "vendor.qti.qspmhal@1.0".