sm8250-common: Import missing libtinyxml DisplayFeature blob
error: "displayfeature.default" depends on undefined module "libtinyxml".
Or did you mean ["libtinyxml2"]?